### ISSUE TITLE
Filter for 'focused review needed' not functional

### ISSUE THREAD

**Issue by marcelrv** [TheSpaghettiDetective/TheSpaghettiDetective#551] opened 2021-12-22 11:16 UTC
**Describe the bug**
Filter for 'focused review needed' shows also items without the focused review needed in the screen.
 
![image](https://user-images.githubusercontent.com/5871213/147083892-90b265bf-a6e7-43d5-ac05-4b297b3b43af.png)

**To Reproduce**
1. load the regular screen
2. select filter in the top right of the screen
3. expect the screen to show only the tumbs according to the filter

**Screenshots**

**Hosting environment (please complete the following information):**
 - OS: Linux/docker image. Self hosted version
 - Version latest from github (22-12-2021)
 - Hardware  PC, 

**Additional context**

**Comment by kennethjiang** [comment] 2021-12-23 02:59
Can you click on the thumb up/down buttons on these timelapses and see if the focused feedback button will show up?

**Comment by marcelrv** [comment] 2021-12-23 08:08
Yes, it shows. There are a few in the list, but I could not get them in the screenshot.

Clicking on them indeed shows the dialog, you click through the various pictures and have them evaluated and submitted at the end. As far as I can see similar to the tsd hosted version.

**Comment by kennethjiang** [comment] 2022-01-01 21:25
@marcelrv Sorry just got back from a vacation.

The focused feedback option won't show unless the thumb up/down is pressed. This is true for both the private server and the TSD cloud.

**Comment by kennethjiang** [comment] 2022-01-01 21:26
Since this is the expected behavior, I'm closing the issue.

**Closed by kennethjiang** 2022-01-01 21:26 UTC
