### ISSUE TITLE
Create DWC/Duet Web Control SBC plugin

### ISSUE THREAD

**Issue by Will-wastelander** [TheSpaghettiDetective/TheSpaghettiDetective#554] opened 2022-01-05 07:49 UTC
https://duet3d.dozuki.com/Wiki/Duet_Web_Control_v2_and_v3_%28DWC%29_Manual
https://github.com/Duet3D/DuetSoftwareFramework/blob/master/PLUGINS.md

**Comment by Will-wastelander** [comment] 2022-01-05 07:59
This would be a SBC based plugin.

**Comment by Will-wastelander** [comment] 2022-01-08 03:48
@kennethjiang Let me know if you need anything for this. I've sent you a few DMs on discord.

**Comment by kennethjiang** [comment] 2022-01-08 16:31
Ok. Thank you @Will-wastelander

**Comment by raymondh2** [comment] 2022-04-26 18:58
Duplicate of #381

**Closed by raymondh2** 2022-04-26 18:58 UTC
Labels: enhancement
