### ISSUE TITLE
OctoPrint_MultiCam does not work with Obico

### ISSUE THREAD

**Issue by Snakn1** [TheSpaghettiDetective/TheSpaghettiDetective#731] opened 2022-12-15 12:44 UTC
hello has anyone else found that the [OctoPrint_MultiCam](https://github.com/mikedmor/OctoPrint_MultiCam) does not like this plugin. I have tried to uninstall both, change the setup but as long as I have This plugin active then multi cam does not show the non main camera, If I disable this one then to other works.  

Logs to follow later today 

I am adding in the logs:
I used a new octopi image, restored my config. I then disabled the Obico. tested it . it worked. I then downloaded the logs. I deleted the logs. I then enabled Obico did a full pi shutdown. powered it off. re powered it on. then tried it. I looked at the logs, changes one setting then tried it again. still not working. I then saved that log. 

My guess id Obico is taking full control of the tcp ports rather then just the ones it needs. if you can maybe exclude the one port 8081 then maybe this will work. 

I do not care ( ok maybe a wish in the future) if I have the choice of the multi cam in the Obico app. I just want it to work locally.
 
[octoprint_Working.log](https://github.com/TheSpaghettiDetective/obico-server/files/10247177/octoprint_Working.log)
[octoprint_not working.log](https://github.com/TheSpaghettiDetective/obico-server/files/10247181/octoprint_not.working.log)

**Comment by kennethjiang** [comment] 2022-12-17 06:41
Compatibility mode needs to be set to "always" for multiple camera situation: https://obico.io/docs/user-guides/streaming-compatibility-mode/#when-should-i-always-stream-in-the-compatibility-mode

Please try it and let me know if the issue is solved.

**Comment by kennethjiang** [comment] 2022-12-20 02:46
Compatibility mode shouldn't be choppy. There is probably something else going on, most likely related to webcam/network configuration. 

Git issues are better for real code bugs, not configuration issues. You will help faster if you write to us support@obico.io (since you are a Pro subscriber) or ask in our discord server. https://obico.io/discord/

**Comment by Snakn1** [comment] 2022-12-20 03:34
Thank you. About 1hr ago I think I found the issue with choppiness. It was
an old plug-in looking for updates that was loaded by my restore config
settings but was not installed when it was restored. I went in and
manually removed it and its data from the system. That helped with the
problem by about 90%. I am thinking the rest is bandwidth in the area due
to the weather. I have until Feb to fully fix this and one other smaller
issue, or downgrade to free.
FYI everyone. It is not about the money, This is a very reasonable price
and useful. But now that I am mostly remote I do not use it as much as I
used to. I want all my local features and when I do use it to monitor
remotely, I still want the full experience.  I hope I can fix this, it is a
great remote tool when you are not at your local network location.

**Comment by kennethjiang** [comment] 2022-12-22 13:28
@Snakn1 Glad that you found the cause. Also glad to know that Obico has been mostly working out for you. :)

BTW when you said you want the full experience, do you mean access the octoprint page? If so, you can use Obico's octoprint tunnel anywhere, in case you didn't know this feature.

I'm closing this ticket. Let me know if you are still experiencing issues. Again the quickest way to get help is usually email (for Pro subscribers) and our discord server (for everyone).

**Closed as completed by kennethjiang** 2022-12-22 13:28 UTC
